### ISSUE TITLE
error 500 on first invoke

### ISSUE THREAD

**Issue by frconil** [frconil/Cachet#1]
Following the setup instructions from Readme.md:

export DB_USERNAME=cachet
export DB_PASSWORD=cachet
export DB_DATABASE=cachet
``` 
 docker run --name mysql -e MYSQL_USER=$DB_USERNAME -e MYSQL_PASSWORD=$DB_PASSWORD -e MYSQL_DATABASE=$DB_DATABASE -d mysql
docker run --link mysql:mysql -e DB_HOST=mysql -e DB_DATABASE=$DB_DATABASE -e DB_USERNAME=$DB_USERNAME -e DB_PASSWORD=$DB_PASSWORD contyard.office.infoxchange.net.au/cachet:1 php artisan migrate

docker run -d --name cachet --link mysql:mysql -p 8000:8000 -e DB_HOST=mysql -e DB_DATABASE=$DB_DATABASE -e DB_USERNAME=$DB_USERNAME -e DB_PASSWORD=$DB_PASSWORD contyard.office.infoxchange.net.au/cachet:7
```
Getting Laravel's error 500 on <docker-host>:8000/index.php and <docker-host>:8000/setup

**Comment by sammcj** [comment]
forked fork for unforking https://github.com/sammcj/Cachet

**Comment by sammcj** [comment]
holy crap building PHP apps is disgusting, all those package managers and upstream requirements.

so fragile. much dev.

**Comment by sammcj** [comment]
Fixed by passing envs through to php-fpm
